services:
  pgdatabase:
    image: postgres:13
    environment:
      POSTGRES_USER: "mitul"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "mitul_db"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    ports:
      - "8085:80"

volumes:
  pgadmin_data: